### ISSUE TITLE
Lab2 замечания

### ISSUE THREAD

**Issue by Andrewbooq** [AnnaGribanova/lab2#1]
Проверил. Как промежуточный вариант неплохо.
Нужно прокомментировать, что делать дальше? Или понятно?

**Comment by AnnaGribanova** [comment]
Напишите, пожалуйста, что делать дальше

**Comment by Andrewbooq** [comment]
1 thread::hardware_concurrency() может вернуть ноль? 
2 функция myFunction запускется параллельно в контексте разных потоков. Нужно придумать математические действия и производить расчеты внутри. Математика может быть любой, главное, чтобы она была достаточно сложной, чтобы считаться хотя бы несколько секунд и должна быть уникальной по отношению к Лабораторным одногрупников.
3 Добавить user-friendly к своей программе. При запуске должно быть понятно: что запущено, сколько потоков, что считаем, каков ожидаемый результат и куда будет выведен результат (в файл, на экран,...)

**Comment by AnnaGribanova** [comment]
Написала проверку на 0, теперь запускается минимум 1 поток
Сделала расчет суммы массива из случайных чисел и вывод сообщений

**Comment by Andrewbooq** [comment]
В целом выглядит правильно, но 2 момента смущают (надо разобраться и исправить):

1 Что происходит в строке? Мы здесь ничего не забыли?
int* arr = new int[ArraySize];

2 У нас 20 различных потоков, в каждом генерируется 10000000 случайных чисел. Потом они суммируются, так? А в output.txt вижу полно одинаковых значений. Здесь явно что-то не так
```
44981801
44981801
44981801
44981801
44981801
44981801
44981801
44981801
44981801
44991416
44981801
44981801
44991416
44991416
44981801
44991416
44991416
44991416
44991416
44991416
```
3 Не вижу Makefile для сборки под Linux

**Comment by AnnaGribanova** [comment]
> В целом выглядит правильно, но 2 момента смущают (надо разобраться и исправить):
> 
> 1 Что происходит в строке? Мы здесь ничего не забыли? int* arr = new int[ArraySize];

Я добавила удаление массива

> 2 У нас 20 различных потоков, в каждом генерируется 10000000 случайных чисел. Потом они суммируются, так? А в output.txt вижу полно одинаковых значений. Здесь явно что-то не так

Сделала случайную генерацию, чтобы числа не повторялись

> 3 Не вижу Makefile для сборки под Linux

Добавила

**Comment by Andrewbooq** [comment]
Теперь всё верно, приходи сдавать. Готовь теорию, связанную с этой лабой, тебя не было на многих лекциях
